# Generated by Django 4.2.1 on 2023-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('Company_name', models.CharField(max_length=50)),
                ('Ram', models.CharField(max_length=200)),
                ('Rom', models.CharField(max_length=200)),
                ('Model_name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=200)),
            ],
        ),
    ]
