# Generated by Django 4.2.1 on 2023-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopmodel',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
