# Generated by Django 4.2.1 on 2023-05-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0002_alter_laptopmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
