# Generated by Django 4.2.1 on 2023-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0003_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='accountno',
            field=models.IntegerField(unique=True),
        ),
    ]
